




import BothHeaders from '@/ui/headerFeature/BothHeaders'
import '../../globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/ui/footer/Footer'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'testing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className} >
        
        
        <BothHeaders/>
         {children}
        <Footer/>

       
      </body>


    </html>
  )
}
