
import NoUserHeader from '@/ui/headerFeature/NoUserHeader'
import '../globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/ui/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body className={inter.className}>
      <NoUserHeader/>
        {children}
      <Footer/>
      </body>
     
    </html>
  )
}
